routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('template');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('user', 'UserController');
Route::resource('product', 'ProductController');
Route::resource('brand', 'BrandController');
Route::resource('category', 'CategoryController');

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $table = 'product';        
    protected $fillable = ['product_name', 'product_spec', 'id_brand','transmision'];
   
    public function brand(){
        return $this->belongsTo('App\Brand', 'id_brand');
    }
    public function category(){
        return $this->belongsToMany('App\Category');
    }
    public function detail_product(){
        return $this->belongsToMany('App\DetailProduct');
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Brand;
use App\Product;
use App\Category;
use App\DetailProduct;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = Product::all();
        return view('product.index_product', compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $brand = Brand::all();
        $category = Category::all();
        return view('product.create_product', compact('brand','category'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->all();
        $product=Product::create($data);
        $category = Category::find($data['category_name']);
        $product->category()->attach($category);
        $color = $data['color'];
       foreach ($color as $key => $color){ 
        $detail_product = new DetailProduct;
        $detail_product->product_id = $product['id'];
        $detail_product->color = $data['color'][$key];        
        $detail_product->icon_color = $data['icon_color'][$key]; 
        $detail_product->foto_mobil = $data['foto_mobil'][$key];        
        $detail_product->harga = $data['harga'][$key];        
        $product->detail_product()->save($detail_product);
       }
      
        // return redirect()->route('product.index_product')->with('alert-success','Berhasil Menambahkan Data!');       
        return $data;
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = Product::where('id',$id)->get();   
        $brand = Brand::all();        
        return view('product.edit_product', compact('data','brand'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/product/create_product.blade.php
@extends('template')   
@section('content') 


<h1>Add Product</h1>
<form action="{{ route('product.store') }}" method="post" enctype="multipart/form-data">
    {{ csrf_field() }}      
   

    <div class="form-group">
    <label for="product_name">Nama Product:</label>
    @if ($errors->any())
    <input type="text" class="form-control {{ $errors->has('product_name') ? 'is-invalid' : 'is-valid' }}" id="product_name" name="product_name" value="{{ old('product_name') }}">
    @else
    <input type="text" class="form-control" id="product_name" name="product_name">
    @endif
    @if ($errors->has('product_name'))
    <div class="invalid-feedback">{{ $errors->first('product_name') }}</div>
    @endif
    </div>   

    <div class="form-group">
    <label for="product_spec">Specifikation:</label>
    @if ($errors->any())
    <input type="text" class="form-control {{ $errors->has('product_spec') ? 'is-invalid' : 'is-valid' }}" id="product_spec" name="product_spec" value="{{ old('product_spec') }}">
    @else
    <input type="text" class="form-control" id="product_spec" name="product_spec">
    @endif
    @if ($errors->has('product_spec'))
    <div class="invalid-feedback">{{ $errors->first('product_spec') }}</div>
    @endif
    </div>   

    <div class="form-group">
    <label for="id_brand">Brand:</label>
    @if ($errors->any())            
    <select name="id_brand" class="custom-select {{ $errors->has('id_brand') ? 'is-invalid' : 'id_brand' }}" id="id_brand" >
    @else
    <select name="id_brand" class="custom-select"> 
    @endif               
    <option selected disabled hidden>Pilih</option>
    @foreach ($brand as $brans) 
    <option value="{{ $brans->id }}">{{ $brans->brand_name  }}</option>
    @endforeach
    </select>
    @if ($errors->has('id_brand'))            
    <div class="invalid-feedback">{{ $errors->first('id_brand') }}</div>
    @endif
    </div> 

    <div class="form-group">
    <label for="transmision">Transmision:</label>
    @if ($errors->any())
    <input type="text" class="form-control {{ $errors->has('transmision') ? 'is-invalid' : 'is-valid' }}" id="transmision" name="transmision" value="{{ old('transmision') }}">
    @else
    <input type="text" class="form-control" id="transmision" name="transmision">
    @endif
    @if ($errors->has('transmision'))
    <div class="invalid-feedback">{{ $errors->first('transmision') }}</div>
     @endif
    </div>   

    <div class="form-grop">
    <label for="category_name">Category:</label>
    @foreach($category as $categorys)
    <div class="checkbox">
    
    <input type="checkbox" name="category_name[]" value="{{$categorys->id}}"> {{$categorys->category_name}}<br>
          
    </div>
    @endforeach
    </div>

    
        <div class="form-group fieldGroup">
                <div class="input-group">
                    <input type="text" name="color[]" class="form-control" placeholder="Warna"/>
                    <input type="file" name="icon_color[]" class="form-control" placeholder="Icon color"/>
                    <input type="file" name="foto_mobil[]" class="form-control" placeholder="Foto Mobil"/>
                    <input type="text" name="harga[]" class="form-control" placeholder="Harga"/>                    
                    <div class="input-group-addon"> 
                        <a href="javascript:void(0)" class="btn btn-success addMore"><span class="glyphicon glyphicon glyphicon-plus" aria-hidden="true"></span> +</a>
                    </div>
                </div>
            </div>
            


    <div class="form-group">
        <button type="submit" class="btn btn-md btn-primary submit">Submit</button>
        <button type="reset" class="btn btn-md btn-danger">Cancel</button>
    </div>
</form>
<div class="form-group fieldGroupCopy" style="display: none;">
        <div class="input-group">
            <input type="text" name="color[]" class="form-control" placeholder="Warna"/>
            <input type="text" name="icon_color[]" class="form-control" placeholder="Icon color"/>
            <input type="text" name="foto_mobil[]" class="form-control" placeholder="Foto Mobil"/>
            <input type="text" name="harga[]" class="form-control" placeholder="Harga"/>            
            <div class="input-group-addon"> 
                <a href="javascript:void(0)" class="btn btn-danger remove"><span class="glyphicon glyphicon glyphicon-remove" aria-hidden="true"></span> -</a>
            </div>
        </div>
    </div>
<script>
    $(document).ready(function(){
    //group add limit
    var maxGroup = 10;
    
    //add more fields group
    $(".addMore").click(function(){
        if($('body').find('.fieldGroup').length < maxGroup){
            var fieldHTML = '<div class="form-group fieldGroup">'+$(".fieldGroupCopy").html()+'</div>';
            $('body').find('.fieldGroup:last').after(fieldHTML);
        }else{
            alert('Maximum '+maxGroup+' groups are allowed.');
        }
    });
    
    //remove fields group
    $("body").on("click",".remove",function(){ 
        $(this).parents(".fieldGroup").remove();
    });
});
        </script>
@endsection

resources/views/product/edit_product.blade.php
@extends('template')
@section('content')
            <h1>Edit Product</h1>
      
            @foreach($data as $datas)
            <form action="{{ route('brand.update', $datas->id) }}" method="post" enctype="multipart/form-data">
                    {{ csrf_field() }}                    
                    {{ method_field('PUT') }}            

                    <div class="form-group">
                    <label for="product_name">Nama Product:</label>
                    @if ($errors->any())
                    <input type="text" class="form-control {{ $errors->has('product_name') ? 'is-invalid' : 'is-valid' }}" id="product_name" name="product_name" value="{{ old('product_name') }}">
                    @else
                    <input type="text" class="form-control" id="product_name" name="product_name" value="{{ $datas->product_name }}">
                    @endif
                    @if ($errors->has('product_name'))
                    <div class="invalid-feedback">{{ $errors->first('product_name') }}</div>
                    @endif
                    </div>    

                    <div class="form-group">
                    <label for="product_spec">Specification :</label>
                    @if ($errors->any())
                    <input type="text" class="form-control {{ $errors->has('product_spec') ? 'is-invalid' : 'is-valid' }}" id="product_spec" name="product_spec" value="{{ old('product_spec') }}">
                    @else
                    <input type="text" class="form-control" id="product_spec" name="product_spec" value="{{ $datas->product_spec }}">
                    @endif
                    @if ($errors->has('product_spec'))
                    <div class="invalid-feedback">{{ $errors->first('product_spec') }}</div>
                    @endif
                    </div>    
        
                    <div class="form-group">
                    <label for="id_brand">Brand:</label>
                    @if ($errors->any())            
                    <select name="id_brand" class="custom-select {{ $errors->has('id_brand') ? 'is-invalid' : 'id_brand' }}" id="id_brand" >
                    @else
                    <select name="id_brand" class="custom-select"> 
                    @endif               
                    <option selected disabled hidden>Pilih</option>
                    @foreach ($brand as $brans) 
                    <option value="{{ $brans->id }}">{{ $brans->brand_name  }}</option>
                    @endforeach
                    </select>
                    @if ($errors->has('id_brand'))            
                    <div class="invalid-feedback">{{ $errors->first('id_brand') }}</div>
                    @endif
                    </div> 

                <div class="form-group">
                     <button type="submit" class="btn btn-md btn-primary">Submit</button>
                     <button type="reset" class="btn btn-md btn-danger">Cancel</button>
                </div>
            </form>
            @endforeach
@endsection

resources/views/product/index_product.blade.php
@extends('template')   
@section('content') 




<section class="main-section">
        <div class="content">
                @if(Session::has('alert-success'))
                <div class="alert alert-success">
                    <strong>{{ \Illuminate\Support\Facades\Session::get('alert-success') }}</strong>
                </div>
            @endif
            <h1>Product</h1>        
            <table class="table table-hover">
                    <thead>
                    <tr>
                        <th>No.</th>
                        <th>Name Product </th>
                        <th>Brand</th>
                        <th>Action</th>
                    </tr>
                    </thead>
                    <tbody>
                    @php $no = 1; @endphp
                    @foreach($data as $datas)
                        <tr>
                            <td>{{ $no++ }}</td>
                            <td>{{ $datas->product_name }}</td>
                            <td>{{ $datas->brand->brand_name }}</td>    
                          
                            <td>
                                <form action="{{ route('product.destroy', $datas->id) }}" method="post">
                                    {{ csrf_field() }}                                                                    
                                    {{ method_field('DELETE') }}
                                    <a href="{{ route('product.edit',$datas->id) }}" class=" btn btn-sm btn-primary">Edit</a>
                                    <button class="btn btn-sm btn-danger" type="submit" onclick="return confirm('Yakin ingin menghapus data?')">Delete</button>
                                </form>
                            </td>
                        </tr>

                        {{-- {{$datas->category}} --}}
                        {{-- {{$datas->detail_product}}      --}}
                    @endforeach
                    </tbody>
                </table>
    
                <a href="/product/create" class="btn btn-sm btn-success">Add Product</a>
                
        </div>
    </section>                     
   
@endsection