routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('template');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('user', 'UserController');
Route::resource('product', 'ProductController');
Route::resource('brand', 'BrandController');
Route::resource('category', 'CategoryController');

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $table = 'category';        
    protected $fillable = ['category_name'];

    public function product(){
        return $this->belongsToMany('App\Product');        
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Category;
use Validator;


class CategoryController extends Controller
{
    public function index()
    {
        $data = Category::all();
        return view('category.index_category', compact('data'));
    }

    public function create()
    {
        return view('category.create_category');
    }

    public function store(Request $request)
    {
        $data = $request->all();
        $validasi = Validator::make($data, [
            'category_name'      => 'required|unique:category',
            
        ]);
        if ($validasi->fails()) {
            return redirect('category/create')
                    ->withInput()
                    ->withErrors($validasi);
        }
        Category::create($data);
        return redirect()->route('category.create')->with('alert-success','Berhasil Menambahkan Data!');        
    
    }

    public function edit()
    {
        $data = Category::all();
        return view('category.edit_category', compact('data'));
    }

    public function update(Request $request, $id)
    {
        $category = Category::findOrFail($id);
        $data = $request->all();

        $validasi = Validator::make($data, [
            'category_name'      => 'required|unique:category,category_name,'. $category->id,
        ]); 
        if ($validasi->fails()) {
            return redirect('category/create')
                    ->withInput()
                    ->withErrors($validasi);
        }
        $category->update($data);
        return redirect()->route('category.index')->with('alert-success','Berhasil Update Data!');        
    }

    public function destroy($id)
    {
        $data = Category::where('id',$id)->first();      
        $data->delete();
        return redirect()->route('category.index')->with('alert-success','Data berhasi dihapus!');   
    }
}

resources/views/category/create_category.blade.php
@extends('template')   
@section('content') 


<h1>Tambah Category</h1>
<form action="{{ route('category.store') }}" method="post" enctype="multipart/form-data">
    {{ csrf_field() }}      
    
    <div class="form-group">
    <label for="category_name">Category:</label>
    @if ($errors->any())
    <input type="text" class="form-control {{ $errors->has('category_name') ? 'is-invalid' : 'is-valid' }}" id="category_name" name="category_name" value="{{ old('category_name') }}">
    @else
    <input type="text" class="form-control" id="category_name" name="category_name" >
    @endif
    @if ($errors->has('category_name'))
    <div class="invalid-feedback">{{ $errors->first('category_name') }}</div>
    @endif
    </div> 

    <div class="form-group">
        <button type="submit" class="btn btn-md btn-primary">Submit</button>
        <button type="reset" class="btn btn-md btn-danger">Cancel</button>
    </div>
    </form>

@endsection

resources/views/category/edit_category.blade.php
@extends('template')
@section('content')
            <h1>Edit Category</h1>
      
            @foreach($data as $datas)
            <form action="{{ route('category.update', $datas->id) }}" method="post" enctype="multipart/form-data">
                    {{ csrf_field() }}                    
                    {{ method_field('PUT') }}            

                <div class="form-group">
                <label for="category_name">Cateegory:</label>
                @if ($errors->any())
                <input type="text" class="form-control {{ $errors->has('category_name') ? 'is-invalid' : 'is-valid' }}" id="category_name" name="category_name" value="{{ old('category_name') }}">
                @else
                <input type="text" class="form-control" id="category_name" name="category_name" value="{{ $datas->category_name }}">
                @endif
                @if ($errors->has('category_name'))
                <div class="invalid-feedback">{{ $errors->first('category_name') }}</div>
                @endif
                </div>   
                

                <div class="form-group">
                     <button type="submit" class="btn btn-md btn-primary">Submit</button>
                     <button type="reset" class="btn btn-md btn-danger">Cancel</button>
                </div>
            </form>
            @endforeach
@endsection

resources/views/category/index_category.blade.php
@extends('template')   
@section('content') 


<section class="main-section">
        <div class="content">
                @if(Session::has('alert-success'))
                <div class="alert alert-success">
                    <strong>{{ \Illuminate\Support\Facades\Session::get('alert-success') }}</strong>
                </div>
            @endif
            <h1>Category</h1>        
            <table class="table table-hover">
                    <thead>
                    <tr>
                        <th>No.</th>
                        <th>Category </th>
                        <th>Action</th>
                    </tr>
                    </thead>
                    <tbody>
                    @php $no = 1; @endphp
                    @foreach($data as $datas)
                        <tr>
                            <td>{{ $no++ }}</td>
                            <td>{{ $datas->category_name }}</td>
                            <td>
                                <form action="{{ route('category.destroy', $datas->id) }}" method="post">
                                    {{ csrf_field() }}                                                                    
                                    {{ method_field('DELETE') }}
                                    <a href="{{ route('category.edit',$datas->id) }}" class=" btn btn-sm btn-primary">Edit</a>
                                    <button class="btn btn-sm btn-danger" type="submit" onclick="return confirm('Yakin ingin menghapus data?')">Delete</button>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
    
                <a href="/category/create" class="btn btn-sm btn-success">Add category</a>
                
        </div>
    </section>
@endsection