routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('template');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('user', 'UserController');
Route::resource('product', 'ProductController');
Route::resource('brand', 'BrandController');
Route::resource('category', 'CategoryController');

app/Brand.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Brand extends Model
{
    protected $table = 'brand';    
    protected $fillable = ['brand_name','brand_foto'];
    
    public function product(){
        return $this->hasMany('App\Product', 'id_brand');
    }
}

app/Http/Controllers/BrandController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Brand;
use Validator;
use Storage;



class BrandController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = Brand::all();
        return view('brand.index_brand', compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view ('brand.create_brand');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
     
        $data = $request->all();
        $validasi = Validator::make($data, [
            'brand_name'      => 'required|unique:brand',
            'brand_foto'      => 'required|image|mimes:jpeg,jpg,bmp,png'
            
        ]);
        if ($validasi->fails()) {
            return redirect('brand/create')
                    ->withInput()
                    ->withErrors($validasi);
        }
        // if ($request->hasFile('brand_foto')){
            // $this->hapusFoto($img);
            $data['brand_foto']= $this->uploadFoto($request);
            
        // }
        Brand::create($data);
        return redirect()->route('brand.index')->with('alert-success','Berhasil Menambahkan Data!');        
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = Brand::where('id',$id)->get();        
        return view('brand.edit_brand', compact('data'));
        
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $brand = Brand::findOrFail($id);
        $img = Brand::where('id',$id)->first();                
        $data = $request->all();

        $validasi = Validator::make($data, [
            'brand_name'      => 'required|unique:brand,brand_name,'. $brand->id,
            'brand_foto'      => 'sometimes|image|mimes:jpeg,jpg,bmp,png'
        ]); 
        if ($validasi->fails()) {
            return redirect('brand/create')
                    ->withInput()
                    ->withErrors($validasi);
        }
        if ($request->hasFile('brand_foto')){
            $this->hapusFoto($img);
            $data['brand_foto']= $this->uploadFoto($request);
            
        }
        
        $brand->update($data);
        return redirect()->route('brand.index')->with('alert-success','Berhasil Update Data!');        
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $data = Brand::where('id',$id)->first();
        $this->hapusFoto($data);        
        $data->delete();
        return redirect()->route('brand.index')->with('alert-success','Data berhasi dihapus!');   
    }

    private function uploadFoto( $request)
	{
		$brand_foto = $request->file('brand_foto');
        $filename = $brand_foto->getClientOriginalName();
        
		if ($request->file('brand_foto')->isValid()) {
            $foto_name   = date('YmdHis'). ".$filename";            
            $request->file('brand_foto')->move("gambar/", $foto_name);
            
			return $foto_name;
			}
			return false;
    }
    
    private function hapusFoto($img)
    {
          $exist = Storage::disk('brand_foto')->exists($img->brand_foto);
  
          if (isset($img->brand_foto) && $exist) {
              $delete = Storage::disk('brand_foto')->delete($img->brand_foto);
              if ($delete) {
                  return true;
              }
              return false;
          }
      }
}

resources/views/brand/create_brand.blade.php
@extends('template')   
@section('content') 


<h1>Tambah Brand</h1>
<form action="{{ route('brand.store') }}" method="post" enctype="multipart/form-data">
    {{ csrf_field() }}      
   
    <div class="form-group">
    <label for="brand_name">Nama Brand:</label>
    @if ($errors->any())
    <input type="text" class="form-control {{ $errors->has('brand_name') ? 'is-invalid' : 'is-valid' }}" id="brand_name" name="brand_name" value="{{ old('brand_name') }}">
    @else
    <input type="text" class="form-control" id="brand_name" name="brand_name" >
    @endif
    @if ($errors->has('brand_name'))
    <div class="invalid-feedback">{{ $errors->first('brand_name') }}</div>
    @endif
    </div> 
    
    <div class="form-group">
    <label for="brand_foto">Brand Logo:</label>
    @if ($errors->any())
    <input type="file" class=" form-control {{ $errors->has('brand_foto') ? 'is-invalid' : 'is-valid' }}" id="brand_foto" name="brand_foto" >
    @else
    <input type="file" class="form-control" id="brand_foto" name="brand_foto">  
    @endif      
    @if ($errors->has('brand_foto'))
    <div class="invalid-feedback">{{ $errors->first('brand_foto') }}</div>
    @endif
    </div>

    <div class="form-group">
    <button type="submit" class="btn btn-md btn-primary">Submit</button>
    <button type="reset" class="btn btn-md btn-danger">Cancel</button>
    </div>
</form>

@endsection

resources/views/brand/edit_brand.blade.php
@extends('template')
@section('content')
            <h1>Edit Brand</h1>
      
            @foreach($data as $datas)
            <form action="{{ route('brand.update', $datas->id) }}" method="post" enctype="multipart/form-data">
                    {{ csrf_field() }}                    
                    {{ method_field('PUT') }}            

                <div class="form-group">
                <label for="brand_name">Nama Brand:</label>
                @if ($errors->any())
                <input type="text" class="form-control {{ $errors->has('brand_name') ? 'is-invalid' : 'is-valid' }}" id="brand_name" name="brand_name" value="{{ old('brand_name') }}">
                @else
                <input type="text" class="form-control" id="brand_name" name="brand_name" value="{{ $datas->brand_name }}">
                @endif
                @if ($errors->has('brand_name'))
                <div class="invalid-feedback">{{ $errors->first('brand_name') }}</div>
                @endif
                </div>    

                <div class="form-group">
                <label for="brand_foto">Brand Logo:</label>
                @if ($errors->any())
                <input type="file" class=" form-control {{ $errors->has('brand_foto') ? 'is-invalid' : 'is-valid' }}" id="brand_foto" name="brand_foto" >
                @else
                <input type="file" class="form-control" id="brand_foto" name="brand_foto">  
                @endif      
                @if ($errors->has('brand_foto'))
                <div class="invalid-feedback">{{ $errors->first('brand_foto') }}</div>
                @endif
                </div>
                

                <div class="form-group">
                     <button type="submit" class="btn btn-md btn-primary">Submit</button>
                     <button type="reset" class="btn btn-md btn-danger">Cancel</button>
                </div>
            </form>
            @endforeach
@endsection

resources/views/brand/index_brand.blade.php
@extends('template')   
@section('content') 




<section class="main-section">
        <div class="content">
                @if(Session::has('alert-success'))
                <div class="alert alert-success">
                    <strong>{{ \Illuminate\Support\Facades\Session::get('alert-success') }}</strong>
                </div>
            @endif
            <h1>Brand</h1>        
            <table class="table table-hover">
                    <thead>
                    <tr>
                        <th>No.</th>
                        <th>Brand </th>
                        <th>Logo</th>
                        <th>Action</th>
                    </tr>
                    </thead>
                    <tbody>
                    @php $no = 1; @endphp
                    @foreach($data as $datas)
                        <tr>
                            <td>{{ $no++ }}</td>
                            <td>{{ $datas->brand_name }}</td>
                            <td>
                                <img src="{{ asset('gambar/' .$datas->brand_foto)}}" style="max-height:150px;max-width:100;"></td>
                            </td>
                            <td>
                                <form action="{{ route('brand.destroy', $datas->id) }}" method="post">
                                    {{ csrf_field() }}                                                                    
                                    {{ method_field('DELETE') }}
                                    <a href="{{ route('brand.edit',$datas->id) }}" class=" btn btn-sm btn-primary">Edit</a>
                                    <button class="btn btn-sm btn-danger" type="submit" onclick="return confirm('Yakin ingin menghapus data?')">Delete</button>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
    
                <a href="/brand/create" class="btn btn-sm btn-success">Add Brand</a>
                
        </div>
    </section>
@endsection