routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('template');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('user', 'UserController');
Route::resource('product', 'ProductController');
Route::resource('brand', 'BrandController');
Route::resource('category', 'CategoryController');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;
use Validator;



class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        {
            $data = User::paginate(10);
            return view('user.user', compact('data'));
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('user.add_user');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
         $data = $request->all();        
         $validasi = Validator::make($data, [
            'email'    => 'required|email|unique:users',
            'name'     => 'required|max:255',
            'password' => 'required|min:6',
          
        ]);
        if ($validasi->fails()) {
            return redirect('user/create')
                    ->withInput()
                    ->withErrors($validasi);
        }

        $data['password'] = bcrypt($data['password']);      
        $user=User::create($data);
        return redirect()->route('user.index')->with('alert-success','Berhasil Menambahkan Data!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = User::where('id',$id)->get();
        return view('user.edit_user', compact('data','departement'));   
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $user = User::findOrFail($id);
        $data = $request->all();


        $validasi = Validator::make($data, [
            'email'      => 'required|email|unique:users,email,'. $data['id'], 
            'name'     => 'required|max:255',
            'password' => 'required|min:6',
         
        ]);
        
        if ($validasi->fails()) {
            return redirect("user/$id/edit")
                    ->withInput()
                    ->withErrors($validasi);
        }

        if ($request->has('password')) {
            // Hash password.
            $data['password'] = bcrypt($data['password']);
        } else {
            // Hapus password (password tidak diupdate).
            $data = array_except($data, ['password']);
        }

        $user->update($data);
        return redirect()->route('user.index')->with('alert-success','Berhasil Update Data!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $data = User::where('id',$id)->first();
        $data->delete();
        return redirect()->route('user.index')->with('alert-success','Data berhasi dihapus!');
    }
}

resources/views/user/add_user.blade.php
@extends('template')   
@section('content') 



<section class="main-section">
                @if(Session::has('alert-success'))
                <div class="alert alert-success">
                    <strong>{{ \Illuminate\Support\Facades\Session::get('alert-success') }}</strong>
                </div>
            @endif
            <h1>Tambah User</h1>
            <form action="{{ route('user.store') }}" method="post" enctype="multipart/form-data">
                {{ csrf_field() }}         
               
                <div class="form-group">
                <label for="name">Nama Lengkap:</label>
                @if ($errors->any())
                <input type="text" class="form-control {{ $errors->has('name') ? 'is-invalid' : 'is-valid' }}" id="name" name="name" value="{{ old('name') }}">
                @else
                <input type="text" class="form-control" id="name" name="name">
                @endif
                @if ($errors->has('name'))
                <div class="invalid-feedback">{{ $errors->first('name') }}</div>
                @endif
                </div>   
              
        
                <div class="form-group">
                <label for="email">Email:</label>
                @if ($errors->any())
                <input type="text" class="form-control {{ $errors->has('email') ? 'is-invalid' : 'is-valid' }}" id="email" name="email" value="{{ old('email') }}">
                @else
                <input type="text" class="form-control" id="email" name="email">
                @endif
                @if ($errors->has('email'))
                <div class="invalid-feedback">{{ $errors->first('email') }}</div>
                @endif
                </div>            

                <div class="form-group">
                <label for="password">Password:</label>
                @if ($errors->any())
                <input type="password" class="form-control {{ $errors->has('password') ? 'is-invalid' : 'is-valid' }}" id="password" name="password">
                @else
                <input type="password" class="form-control" id="password" name="password">
                @endif
                @if ($errors->has('password'))
                <div class="invalid-feedback">{{ $errors->first('password') }}</div>
                @endif
                </div>

                <div class="form-group">
                <button type="submit" class="btn btn-md btn-primary">Submit</button>
                <button type="reset" class="btn btn-md btn-danger">Cancel</button>
                </div>
            </form>
        </div>
    </section>
    @endsection
    

resources/views/user/edit_user.blade.php
@extends('template')
@section('content')

<section class="main-section">
        
            <h1>Edit User</h1>
            <hr>
            @foreach($data as $datas)
            <form action="{{ route('user.update', $datas->id) }}" method="post" enctype="multipart/form-data">
                    {{ csrf_field() }}                    
                          {{ method_field('PUT') }}    
             @if (isset($data))
            <input type="hidden" id="id" name="id" value="{{ $datas->id }}">                          
            @endif
          
            <div class="form-group">
            <label for="name">Nama Lengkap:</label>
            @if ($errors->any())
            <input type="text" class="form-control {{ $errors->has('name') ? 'is-invalid' : 'is-valid' }}" id="name" name="name" value="{{ old('name') }}">
            @else
            <input type="text" class="form-control" id="name" name="name" value="{{ $datas->name }}">
            @endif
            @if ($errors->has('name'))
            <div class="invalid-feedback">{{ $errors->first('name') }}</div>
            @endif
            </div>    

            <div class="form-group">
            <label for="email">Email:</label>
            @if ($errors->any())
            <input type="text" class="form-control {{ $errors->has('email') ? 'is-invalid' : 'is-valid' }}" id="email" name="email" value="{{ old('email') }}">
            @else
            <input type="text" class="form-control" id="email" name="email" value="{{ $datas->email }}">
            @endif
            @if ($errors->has('email'))
            <div class="invalid-feedback">{{ $errors->first('email') }}</div>
            @endif
            </div>    
            
            <div class="form-group">
            <label for="password">Password:</label>
            @if ($errors->any())
            <input type="password" class="form-control {{ $errors->has('password') ? 'is-invalid' : 'is-valid' }}" id="password" name="password">
            @else
            <input type="password" class="form-control" id="password" name="password">
            @endif
            @if ($errors->has('password'))
            <div class="invalid-feedback">{{ $errors->first('password') }}</div>
            @endif
            </div>
            
            <div class="form-group">
            <button type="submit" class="btn btn-md btn-primary">Submit</button>
            <button type="reset" class="btn btn-md btn-danger">Cancel</button>
            </div>
            </form>
            @endforeach
</section>
@endsection

resources/views/user/user.blade.php
@extends('template')   
@section('content') 

<section class="main-section">
    <div class="content col-md-12 col-sm-12 col-12">
            <h1>User</h1>            
            @if(Session::has('alert-success'))
            <div class="alert alert-success">
                <strong>{{ \Illuminate\Support\Facades\Session::get('alert-success') }}</strong>
            </div>
        @endif
        <table class="table table-hover">
                <thead>
                <tr>
                    <th>No.</th>
                    <th>Nama Lengkap</th>
                    <th>Email</th>                    
                    <th>Aksi</th>
                </tr>
                </thead>
                <tbody>
                @php $no = 1; @endphp
                @foreach($data as $datas)
                    <tr>
                        <td>{{ $no++ }}</td>
                        <td>{{ $datas->name }}</td>       
                        <td>{{ $datas->email }}</td>                                  
                        <td>
                            <form action="{{ route('user.destroy', $datas->id) }}" method="post">
                                {{ csrf_field() }}                                                                    
                                {{ method_field('DELETE') }}
                                <a href="{{ route('user.edit',$datas->id) }}" class=" btn btn-sm btn-primary">Edit</a>
                                <button class="btn btn-sm btn-danger" type="submit" onclick="return confirm('Yakin ingin menghapus data?')">Delete</button>
                            </form>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
         
            <a href="/user/create" class="btn btn-sm btn-success">Tambah User</a>            
    </div>
</section>
@endsection